# Generated by Django 2.1.15 on 2021-09-21 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym_or_club', '0003_auto_20210921_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_or_club', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
                ('member', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='gym_or_club.member')),
            ],
        ),
    ]
