# Generated by Django 3.2.8 on 2021-11-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20211027_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
    ]
