# Generated by Django 2.1.15 on 2021-09-21 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_or_club', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('plan', models.CharField(choices=[('Free', 'Free'), ('Monthly', 'Monthly'), ('Quaterly', 'Quaterly'), ('Yearly', 'Yearly')], default='Free', max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(default='Cash On Delivery', max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('member', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='gym_or_club.members')),
            ],
        ),
    ]
