# Generated by Django 2.1.15 on 2021-09-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_or_club', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='members',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='membership',
            name='date',
            field=models.DateField(),
        ),
    ]
