# Generated by Django 2.1.15 on 2021-09-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_or_club', '0002_auto_20210921_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='payment_id',
            field=models.CharField(max_length=100),
        ),
    ]
