# Generated by Django 2.1.15 on 2021-09-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_or_club', '0004_auto_20210921_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='due_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_id',
            field=models.CharField(default='Free', max_length=100),
        ),
    ]
