# Generated by Django 2.1.15 on 2021-09-21 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_or_club', '0005_auto_20210921_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='gym_or_club.member'),
        ),
    ]
