# Generated by Django 2.1.15 on 2021-10-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True)),
                ('doa', models.DateField(blank=True)),
                ('phone_number', models.BigIntegerField()),
                ('emergency_phone_number', models.BigIntegerField(blank=True)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(blank=True, max_length=100)),
                ('fathers_name', models.CharField(blank=True, max_length=100)),
                ('spouses_name', models.CharField(blank=True, max_length=100)),
                ('plan', models.CharField(choices=[('Monthly', 'Monthly'), ('Quaterly', 'Quaterly'), ('Yearly', 'Yearly')], max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True)),
                ('amount', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Online Payment', 'Online Payment')], max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
