# Generated by Django 2.1.15 on 2021-10-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='fathers_name',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='mothers_name',
            new_name='mother_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='spouses_name',
            new_name='spouse_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date',
        ),
    ]
