# Generated by Django 2.1.15 on 2021-10-08 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('members', '0002_auto_20211008_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gym',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
