# Generated by Django 2.1.15 on 2021-10-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_client_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='amount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='doa',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='emergency_phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Online Payment', 'Online Payment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='plan',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Quaterly', 'Quaterly'), ('Yearly', 'Yearly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
