# Generated by Django 2.1.15 on 2021-10-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20211009_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
