# Generated by Django 2.1.15 on 2021-10-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20211017_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_membership',
            name='date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
