# Generated by Django 2.1.15 on 2021-10-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_client_membership_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_membership',
            name='discount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client_membership',
            name='final_amount',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
