# Generated by Django 2.1.15 on 2021-10-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20211023_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_membership',
            name='discount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
