# Generated by Django 3.2.8 on 2021-10-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20211023_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subscription',
            field=models.CharField(default='Over', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client_membership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
