# Generated by Django 3.2.8 on 2021-10-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_client_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
