# Generated by Django 3.2.8 on 2021-10-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_client_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='plan',
        ),
        migrations.AddField(
            model_name='client',
            name='active',
            field=models.CharField(default='True', max_length=50),
        ),
    ]
